name: CI
on:
  push:
  pull_request:

jobs:
  deno-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Check types
        run: deno check denops
      - name: Lint
        run: deno lint denops
      - name: Check code formats
        run: deno fmt denops --check
